#% text_encoding = iso8859_1


:title			Smallworld Ninja (1.0.6)

:quit			Quit
:score			Score: #1
:start_time		Time: 0:00  
:time_0			Time: #1:0#2
:time			Time: #1:#2
:fps			#1 fps

:combo			Combo +#1
:combo_collection	#1 Combo +#2

:classic_mode		Classic Mode
:classic		Classic
:classic_help		No time limit. 3 misses and you're out.

:fury_mode		Fury Mode
:fury			Fury
:fury_help		90 seconds. Hit as many geometries as possible.

:terms			Terms and Conditions:#nThe SWIFT team assumes no liability or responsibility for any damages to Smart Boards whilst using this software.

:start			Start
:game_over		Game Over
:time_up		Time's Up
:continue		Continue
:final_score		You scored #1 and achieved the rank of #2.

:beginner		Beginner
:intermediate		Intermediate
:advanced		Advanced
:expert			Expert
:master			Master
:legend			Legend
